controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# home:
#     path: /
#     controller: App\Controller\WebController::home

soft-skills:
    path: /soft-skills
    controller: App\Controller\WebController::softSkills